import Header from "@/components/Layout/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Footer from "@/components/Layout/Footer";
import Head from "next/head";

export const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body
        className={`${rubik.className} bg-lightOrange  text-primaryGreen m-0 p-0`}
      >
        <Header />
        <div className="!w-screen !overflow-x-hidden">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
